from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class SkillMeta:
    name: str
    description: str
    skill_dir: Path
    skill_md_text: str
    reference_files: tuple[Path, ...]


def _parse_frontmatter(text: str) -> dict[str, str]:
    lines = text.splitlines()
    if len(lines) < 3 or lines[0].strip() != "---":
        raise ValueError("SKILL.md missing YAML frontmatter delimiter '---' on first line")
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        raise ValueError("SKILL.md missing YAML frontmatter closing delimiter '---'")

    meta: dict[str, str] = {}
    for raw in lines[1:end]:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        meta[k.strip()] = v.strip().strip('"').strip("'")
    return meta


def _load_skill_meta(skill_dir: Path) -> SkillMeta:
    skill_md = skill_dir / "SKILL.md"
    text = skill_md.read_text(encoding="utf-8")
    fm = _parse_frontmatter(text)
    name = fm.get("name", "").strip()
    description = fm.get("description", "").strip()
    if not name:
        raise ValueError(f"Missing frontmatter field 'name' in {skill_md}")
    if not description:
        raise ValueError(f"Missing frontmatter field 'description' in {skill_md}")
    references_dir = skill_dir / "references"
    reference_files = tuple(sorted(references_dir.glob("*.md"))) if references_dir.exists() else ()
    return SkillMeta(
        name=name,
        description=description,
        skill_dir=skill_dir,
        skill_md_text=text,
        reference_files=reference_files,
    )


def build_catalog_md(skills: list[SkillMeta]) -> str:
    lines: list[str] = []
    lines.append("# 技能目录 / Skill Catalog")
    lines.append("")
    lines.append("本页由 `scripts/generate_skill_catalog.py` 自动生成。不要手工编辑。")
    lines.append("")
    lines.append("This page is generated by `scripts/generate_skill_catalog.py`; do not edit it manually.")
    lines.append("")
    for s in skills:
        refs = "；含理论依据 / includes research basis" if s.reference_files else ""
        lines.append(f"- **[`{s.name}`](./{s.name}.md)**: {s.description} {refs}".rstrip())
    lines.append("")
    return "\n".join(lines)


def build_skill_page_md(skill: SkillMeta) -> str:
    lines: list[str] = []
    lines.append(f"# `{skill.name}`")
    lines.append("")
    lines.append(skill.description)
    lines.append("")
    lines.append("本页由 `scripts/generate_skill_catalog.py` 自动生成。不要手工编辑。")
    lines.append("")
    lines.append("This page is generated from the skill folder. It includes the executable skill instructions and any bundled research notes.")
    lines.append("")
    lines.append("## 快速查看 / Quick View")
    lines.append("")
    lines.append(f"- 技能目录 / Skill folder: `skills/{skill.name}/`")
    lines.append(f"- 说明文件 / Skill file: `skills/{skill.name}/SKILL.md`")
    if skill.reference_files:
        lines.append("- 理论依据 / Research basis:")
        for ref in skill.reference_files:
            lines.append(f"  - `skills/{skill.name}/references/{ref.name}`")
    else:
        lines.append("- 理论依据 / Research basis: no bundled reference file.")
    lines.append("")
    lines.append("## SKILL.md（原文）")
    lines.append("")
    lines.append("```")
    lines.append(skill.skill_md_text.rstrip())
    lines.append("```")
    lines.append("")
    if skill.reference_files:
        lines.append("## 理论依据 / Research Basis")
        lines.append("")
        for ref in skill.reference_files:
            lines.append(f"### `{ref.name}`")
            lines.append("")
            lines.append(ref.read_text(encoding="utf-8").rstrip())
            lines.append("")
    return "\n".join(lines)


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    skills_root = repo_root / "skills"
    docs_catalog = repo_root / "docs" / "skills" / "catalog.md"
    docs_skills_dir = repo_root / "docs" / "skills"

    skill_dirs = sorted([p for p in skills_root.iterdir() if p.is_dir()])
    skills = [_load_skill_meta(p) for p in skill_dirs if (p / "SKILL.md").exists()]
    skills_sorted = sorted(skills, key=lambda s: s.name)

    docs_skills_dir.mkdir(parents=True, exist_ok=True)
    docs_catalog.write_text(build_catalog_md(skills_sorted), encoding="utf-8")
    for s in skills_sorted:
        (docs_skills_dir / f"{s.name}.md").write_text(build_skill_page_md(s), encoding="utf-8")


if __name__ == "__main__":
    main()
